### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by nkry** [nkry/pub-kirby#1]
- [x] Tidy up gulp file (loop through files dynamically)
- [x] Separate assets folder into a dist folder
- [x] Import/require JS libs
- [x] Build home page/menu stuff
- [ ] Work out ajax/routing
- [x] Set up deployment workflow
